# Specify a base image
FROM node:20-alpine

WORKDIR /app

# Copy only dependency manifests
COPY package.json ./

# Clean npm state + install
RUN npm cache clean --force \
    && npm install
# RUN npm install || (cat /root/.npm/_logs/* && exit 1)

# Install some depenendencies
COPY ./ ./

# Default command
CMD ["npm", "start"]
